#!/bin/sh
#

set -e 		# fail on any error

case "$1" in
	purge)
		ifelse(M4_COMPANY_NAME, ONLYOFFICE,
		rm -fr /home/*/.local/share/M4_DESKTOPEDITORS_PREFIX,
		rm -fr /home/*/.local/share/M4_PACKAGE_NAME)
	;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  	:
	;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
