#include "version.h"

#define IDI_MAINICON          101
#define IDI_WELCOME           102

#define IDT_TRANSLATIONS      10001

#define APP_LAUNCH_NAME           "\\DesktopEditors.exe"

#define CAPTION
#define MSG_ERR_SYSTEM
#define MSG_ERR_ALREADY_RUNNING
#define MSG_ERR_TRY_CLOSE_APP
#define MSG_ERR_CLOSE_APP
#define MSG_REMOVE
#define MSG_REPAIR
#define MSG_UPDATE
#define LABEL_DOWNLOAD
#define LABEL_INSTALL
#define LABEL_UPDATING
#define LABEL_REPAIRING
#define LABEL_UNINSTLING
#define LABEL_UPDATE_COMPL
#define LABEL_REPAIR_COMPL
#define LABEL_UNINST_COMPL
#define LABEL_VERSION
#define LABEL_UNKN_VER
#define LABEL_UNKN_PACK
#define LABEL_NO_OPTIONS
#define LABEL_NO_VER_AVAIL
#define LABEL_WARN_CLOSE
#define LABEL_ALMOST_DONE
#define LABEL_INSTALL_COMPL
#define LABEL_ERR_PROD_CODE
#define LABEL_ERR_PACK_NAME
#define LABEL_ERR_INSTALL
#define LABEL_ERR_UNINST
#define LABEL_ERR_COMMON
#define LABEL_ERR_RUNNING
#define LABEL_ERR_CANCELLED
#define BUTTON_INSTALL
#define BUTTON_CANCEL
#define BUTTON_APPLY
#define BUTTON_CLOSE
#define BUTTON_BACK
#define RADIO_UPDATE
// #define RADIO_REPAIR
#define RADIO_UNINST
#define CHECK_SILENT
#define CHECK_LAUNCH
#define CHECK_CLR_DATA
#define CHECK_CLR_STNGS
#define CHECK_CLR_ALL
