fin = open("DesktopEditorsPortable.evb", "rt")
data = fin.read()
fin.close()
fin = open("DesktopEditorsPortable.evb", "wt")
data = data.replace('<ActiveX>False</ActiveX>', '')
data = data.replace('<ActiveXInstall>False</ActiveXInstall>', '')
data = data.replace('<Action>0</Action>', '')
data = data.replace('<OverwriteDateTime>False</OverwriteDateTime>', '')
data = data.replace('<OverwriteAttributes>False</OverwriteAttributes>', '')
data = data.replace('<PassCommandLine>False</PassCommandLine>', '')
data = data.replace('<HideFromDialogs>0</HideFromDialogs>', '')
fin.write(data)
fin.close()