name: check
on: push
jobs:
  spellchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup aspell
        run: sudo apt-get -y update && sudo apt-get -y install aspell aspell-en aspell-ru
      - name: Run spellchecker for Windows changelogs
        run: |
          echo "::group::English"
          for d in win-linux/package/windows/update/changes/*/ ; do
            echo "Checking ${d}en.html"
            SPELLCHECK_OUT=$(cat ${d}en.html \
              | aspell --lang=en --encoding=utf-8 \
                --mode=html --personal=./.aspell.en.pws list)
            echo $SPELLCHECK_OUT
          done
          echo "::group::Russian"
          for d in win-linux/package/windows/update/changes/*/ ; do
            echo "Checking ${d}ru.html"
            SPELLCHECK_OUT=$(cat ${d}ru.html \
              | aspell --lang=ru --encoding=utf-8 \
                --mode=html --personal=./.aspell.ru.pws list)
            echo $SPELLCHECK_OUT
          done
      - name: Run spellchecker for macOS changelogs
        run: |
          echo "::group::English"
          for d in macos/ONLYOFFICE/update/updates/ONLYOFFICE/changes/*/ ; do
            echo "Checking ${d}ReleaseNotes.html"
            SPELLCHECK_OUT=$(cat ${d}ReleaseNotes.html \
              | aspell --lang=en --encoding=utf-8 \
                --mode=html --personal=./.aspell.en.pws list)
            echo $SPELLCHECK_OUT
          done
          echo "::group::Russian"
          for d in macos/ONLYOFFICE/update/updates/ONLYOFFICE/changes/*/ ; do
            echo "Checking ${d}ReleaseNotesRU.html"
            SPELLCHECK_OUT=$(cat ${d}ReleaseNotesRU.html \
              | aspell --lang=ru --encoding=utf-8 \
                --mode=html --personal=./.aspell.ru.pws list)
            echo $SPELLCHECK_OUT
          done
